"""Reference Infrastructure Abstraction — Protocols for ACS, RADIUS, DHCP/DNS, SIP, Traffic, NTP, Fileserver."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol, runtime_checkable


@dataclass
class DHCPLease:
    mac: str
    ip: str
    hostname: str
    lease_expires: float  # unix timestamp


@dataclass
class TrafficResult:
    throughput_mbps: float
    latency_ms: float
    jitter_ms: float
    packet_loss_percent: float


@dataclass
class SIPCallResult:
    success: bool
    duration_s: float
    codec: str
    mos_score: float


@runtime_checkable
class ACSService(Protocol):
    def bootstrap_cpe(self, cpe_serial: str) -> dict[str, Any]: ...
    def get_parameter_values(self, cpe_serial: str, paths: list[str]) -> dict[str, Any]: ...
    def set_parameter_values(self, cpe_serial: str, params: dict[str, Any]) -> None: ...
    def add_object(self, cpe_serial: str, path: str) -> int: ...
    def delete_object(self, cpe_serial: str, path: str) -> None: ...
    def reboot(self, cpe_serial: str) -> None: ...
    def download(self, cpe_serial: str, url: str, file_type: str) -> None: ...
    def schedule_inform(self, cpe_serial: str, delay_s: int) -> None: ...
    def get_notifications(self, cpe_serial: str) -> list[dict[str, Any]]: ...
    def run_diagnostics(self, cpe_serial: str, diag_type: str, params: dict[str, Any]) -> dict[str, Any]: ...


@runtime_checkable
class RADIUSService(Protocol):
    def add_user(self, username: str, password: str, attributes: dict[str, str] | None = None) -> None: ...
    def remove_user(self, username: str) -> None: ...
    def authenticate(self, username: str, password: str) -> bool: ...


@runtime_checkable
class DHCPService(Protocol):
    def set_pool(self, subnet: str, start: str, end: str, lease_time_s: int = 86400) -> None: ...
    def add_static_lease(self, mac: str, ip: str) -> None: ...
    def get_leases(self) -> list[DHCPLease]: ...
    def set_option(self, option_code: int, value: str) -> None: ...
    def flush_leases(self) -> None: ...


@runtime_checkable
class TrafficEndpoint(Protocol):
    def start_server(self, port: int = 5201, protocol: str = "tcp") -> None: ...
    def stop_server(self) -> None: ...
    def run_client(self, target_ip: str, duration_s: int, protocol: str = "tcp", parallel: int = 1) -> TrafficResult: ...


@runtime_checkable
class SIPService(Protocol):
    def register(self, extension: str, password: str) -> None: ...
    def make_call(self, from_ext: str, to_ext: str, duration_s: float = 5.0) -> SIPCallResult: ...
    def hangup(self, call_id: str) -> None: ...


@runtime_checkable
class NTPService(Protocol):
    def get_time(self) -> float: ...  # unix timestamp
    def is_synchronized(self) -> bool: ...


@runtime_checkable
class FileServer(Protocol):
    def put_file(self, filename: str, content: bytes) -> str: ...  # returns URL
    def delete_file(self, filename: str) -> None: ...
    def get_url(self, filename: str) -> str: ...
