"""DUT (CPE) Abstract Interface."""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from cpe_ta.dut.capabilities import CapabilitySet


@runtime_checkable
class CPE(Protocol):
    """Unified CPE interface — vendor/model differences are hidden here."""

    @property
    def dut_id(self) -> str: ...

    @property
    def capabilities(self) -> CapabilitySet: ...

    def factory_reset(self, wait_s: float = 120.0) -> None: ...
    def power_off(self) -> None: ...
    def power_on(self) -> None: ...
    def power_cycle(self, delay_s: float = 5.0) -> None: ...
    def config_backup(self) -> dict[str, Any]: ...
    def config_restore(self, config: dict[str, Any]) -> None: ...
    def fw_flash(self, firmware_path: str, bank: str = "primary") -> None: ...
    def fw_rollback(self) -> None: ...
    def get_console_metrics(self) -> dict[str, float]: ...  # cpu_percent, ram_percent
    def get_wan_ip(self) -> str | None: ...
    def get_parameter(self, path: str) -> Any: ...
    def set_parameter(self, path: str, value: Any) -> None: ...
